import flet as ft

menu = ft.AppBar(
    toolbar_height=50,
    title=ft.Row([
        ft.Image('unnamed.png',width=100,height=50)
        ,
        ft.Container(
            content=ft.ElevatedButton('Home',
                                      icon=ft.icons.HOME,
                                      style=ft.ButtonStyle(
                                        shape=ft.RoundedRectangleBorder(radius=1)
                                                            ),
                                        height=50
                                        )
                        ),
        ft.Container(
            content=ft.ElevatedButton('Portais',
                                      icon=ft.icons.DASHBOARD,
                                      style=ft.ButtonStyle(
                                        shape=ft.RoundedRectangleBorder(radius=1)
                                                            ),
                                        height=50
                                        )
                        ),
        ft.Container(
            content=ft.ElevatedButton('Minhas tarefas',
                                      icon=ft.icons.CHECK,
                                      style=ft.ButtonStyle(
                                        shape=ft.RoundedRectangleBorder(radius=1)
                                                            ),
                                        height=50
                                        )
                        ),
        ft.Container(
            content=ft.ElevatedButton('Componentes',
                                      icon=ft.icons.EMOJI_EVENTS,
                                      style=ft.ButtonStyle(
                                        shape=ft.RoundedRectangleBorder(radius=1)
                                                            ),
                                        height=50
                                        )
                        ),
        ft.Container(
            content=ft.ElevatedButton('Atalhos',
                                      icon=ft.icons.BOLT,
                                      style=ft.ButtonStyle(
                                        shape=ft.RoundedRectangleBorder(radius=1)
                                                            ),
                                        height=50
                                        )
                        ),
        ft.Container(
            content=ft.TextField(label='Pesquisar',
                                 suffix_icon=ft.icons.SEARCH,
                                 height=40
                                        )
                        ),
        ft.Container(
            content=ft.ElevatedButton(' ',icon=ft.icons.NOTIFICATIONS,
                                      style=ft.ButtonStyle(
                                        shape=ft.RoundedRectangleBorder(radius=1)
                                                            ),
                                        width=55,
                                        height=50
                                        ),
                                        alignment=ft.alignment.center
                        ),
        ft.Container(
            content=ft.ElevatedButton(' ',icon=ft.icons.EXPLORE,
                                      style=ft.ButtonStyle(
                                        shape=ft.RoundedRectangleBorder(radius=1)
                                                            ),
                                        width=55,
                                        height=50
                                        ),
                                        alignment=ft.alignment.center
                        ),
        ft.Container(
            content=ft.ElevatedButton(' ',icon=ft.icons.HELP,
                                      style=ft.ButtonStyle(
                                        shape=ft.RoundedRectangleBorder(radius=1)
                                                            ),
                                        width=55,
                                        height=50
                                        ),
                                        alignment=ft.alignment.center
                        ),
        ft.Container(
            content=ft.ElevatedButton(' ',icon=ft.icons.SCHOOL,
                                      style=ft.ButtonStyle(
                                        shape=ft.RoundedRectangleBorder(radius=1)
                                                            ),
                                        width=55,
                                        height=50
                                        ),
                                        alignment=ft.alignment.center
                        ),
        ft.Container(
            content=ft.Image('empty.png',
                             width=60,
                             height=50
                             )
                        )
                        ],
                        spacing=1)
    )